version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "bullseye"
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: host

  mongo:
    image: mongo:5.0.6
    restart: unless-stopped
    volumes:
      - ../data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: microservice 
      MONGO_INITDB_ROOT_PASSWORD: microservice
    